### ISSUE TITLE
thank you for bot but not working

### ISSUE THREAD

**Issue by HandR** [inhydrox/discord-music#1]
bot not join channel
i used !play bela ciao
not join channel
can fix ?
i get to glitch 
https://glitch.com/edit/#!/inhydrox-discord-music-3?path=commands/clear-queue.js:1:0

**Comment by HandR** [comment]
https://discord.gg/7NVUUUk

**Comment by inhydrox** [comment]
What is the error?

**Comment by inhydrox** [comment]
I updated the package.json file, It should work now!

**Comment by inhydrox** [comment]
If you still face error, join my server https://discord.gg/VdNadk2
