### ISSUE TITLE
Can you add invite bot command 

### ISSUE THREAD

**Issue by sam920829** [inhydrox/discord-music#8]
Is your feature request related to a problem? Please describe.

Describe the solution you'd like

Describe alternatives you've considered

Additional context

Because if someone wants to invite our bot to his server.. that's why

**Comment by inhydrox** [comment]
What do you really mean by that?

**Comment by inhydrox** [comment]
I understand the title but what you have written in description my mind can't process that

**Comment by inhydrox** [comment]
Anyways I have added an invite command you can configure the links in `config.js` file.
