### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by sam920829** [inhydrox/discord-music#9]
SyntaxError: Unexpected string
[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\user\Downloads\discord-music-master\discord-music-master\index.js:5:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m

C:\Users\user\Downloads\discord-music-master\discord-music-master>pause

**Comment by inhydrox** [comment]
I cannot reproduce the error.
